http:
  port: 7000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints

  inventoryApi:                 # name, used as reference in pipeline
    host: 'localhost'           # required, '*' will not check for host name
    paths: /details             # optional, by default will serve all requests - same as *
  paymentApi:                   # name, used as reference in pipeline
    host: 'localhost'           # wildcard pattern support
    paths: '/payment'
  blogApi:                      # name, used as reference in pipeline
    host: 'localhost'
    paths: '/insertblog'         # string or array of strings

serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  inventoryService:                       # name, used as a reference in pipeline
    url: "http://localhost:7003"
  paymentService:                         # name, used as a reference in pipeline
    url: "http://localhost:7004"                            # multiple urls can be used with load balancing
  blogService:
    url: "http://localhost:7002"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  inventorypipeline:
    apiEndpoints:
      - inventoryApi
    policies:
      -
        proxy: #policy name
          -    # array of objects with condition/action properties
            action:
              serviceEndpoint: inventoryService
  blogpipeline:
    apiEndpoints:
      - blogApi
    policies:
      -
        proxy:
          -
            action:
              serviceEndpoint: blogService
  paymentpipeline:
    apiEndpoints:
      - paymentApi
    policies:
      -
        proxy:
          -
            action:
              serviceEndpoint: paymentService
